SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

CREATE TABLE IF NOT EXISTS `countries` (
  `iso` varchar(2) character set utf8 NOT NULL,
  `name` varchar(80) character set utf8 NOT NULL,
  `iso3` varchar(3) character set utf8 default NULL,
  `numcode` smallint(6) default NULL,
  PRIMARY KEY  (`iso`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `countries` (`iso`, `name`, `iso3`, `numcode`) VALUES
('AF', 'Afghanistan', 'AFG', 4),
('AL', 'Albania', 'ALB', 8),
('DZ', 'Algeria', 'DZA', 12),
('AS', 'American Samoa', 'ASM', 16),
('AD', 'Andorra', 'AND', 20),
('AO', 'Angola', 'AGO', 24),
('AI', 'Anguilla', 'AIA', 660),
('AQ', 'Antarctica', NULL, NULL),
('AG', 'Antigua and Barbuda', 'ATG', 28),
('AR', 'Argentina', 'ARG', 32),
('AM', 'Armenia', 'ARM', 51),
('AW', 'Aruba', 'ABW', 533),
('AU', 'Australia', 'AUS', 36),
('AT', 'Austria', 'AUT', 40),
('AZ', 'Azerbaijan', 'AZE', 31),
('BS', 'Bahamas', 'BHS', 44),
('BH', 'Bahrain', 'BHR', 48),
('BD', 'Bangladesh', 'BGD', 50),
('BB', 'Barbados', 'BRB', 52),
('BY', 'Belarus', 'BLR', 112),
('BE', 'Belgium', 'BEL', 56),
('BZ', 'Belize', 'BLZ', 84),
('BJ', 'Benin', 'BEN', 204),
('BM', 'Bermuda', 'BMU', 60),
('BT', 'Bhutan', 'BTN', 64),
('BO', 'Bolivia', 'BOL', 68),
('BA', 'Bosnia and Herzegovina', 'BIH', 70),
('BW', 'Botswana', 'BWA', 72),
('BV', 'Bouvet Island', NULL, NULL),
('BR', 'Brazil', 'BRA', 76),
('IO', 'British Indian Ocean Territory', NULL, NULL),
('BN', 'Brunei Darussalam', 'BRN', 96),
('BG', 'Bulgaria', 'BGR', 100),
('BF', 'Burkina Faso', 'BFA', 854),
('BI', 'Burundi', 'BDI', 108),
('KH', 'Cambodia', 'KHM', 116),
('CM', 'Cameroon', 'CMR', 120),
('CA', 'Canada', 'CAN', 124),
('CV', 'Cape Verde', 'CPV', 132),
('KY', 'Cayman Islands', 'CYM', 136),
('CF', 'Central African Republic', 'CAF', 140),
('TD', 'Chad', 'TCD', 148),
('CL', 'Chile', 'CHL', 152),
('CN', 'China', 'CHN', 156),
('CX', 'Christmas Island', NULL, NULL),
('CC', 'Cocos (Keeling) Islands', NULL, NULL),
('CO', 'Colombia', 'COL', 170),
('KM', 'Comoros', 'COM', 174),
('CG', 'Congo', 'COG', 178),
('CD', 'Congo, the Democratic Republic of the', 'COD', 180),
('CK', 'Cook Islands', 'COK', 184),
('CR', 'Costa Rica', 'CRI', 188),
('CI', 'Cote D''Ivoire', 'CIV', 384),
('HR', 'Croatia', 'HRV', 191),
('CU', 'Cuba', 'CUB', 192),
('CY', 'Cyprus', 'CYP', 196),
('CZ', 'Czech Republic', 'CZE', 203),
('DK', 'Denmark', 'DNK', 208),
('DJ', 'Djibouti', 'DJI', 262),
('DM', 'Dominica', 'DMA', 212),
('DO', 'Dominican Republic', 'DOM', 214),
('EC', 'Ecuador', 'ECU', 218),
('EG', 'Egypt', 'EGY', 818),
('SV', 'El Salvador', 'SLV', 222),
('GQ', 'Equatorial Guinea', 'GNQ', 226),
('ER', 'Eritrea', 'ERI', 232),
('EE', 'Estonia', 'EST', 233),
('ET', 'Ethiopia', 'ETH', 231),
('FK', 'Falkland Islands (Malvinas)', 'FLK', 238),
('FO', 'Faroe Islands', 'FRO', 234),
('FJ', 'Fiji', 'FJI', 242),
('FI', 'Finland', 'FIN', 246),
('FR', 'France', 'FRA', 250),
('GF', 'French Guiana', 'GUF', 254),
('PF', 'French Polynesia', 'PYF', 258),
('TF', 'French Southern Territories', NULL, NULL),
('GA', 'Gabon', 'GAB', 266),
('GM', 'Gambia', 'GMB', 270),
('GE', 'Georgia', 'GEO', 268),
('DE', 'Germany', 'DEU', 276),
('GH', 'Ghana', 'GHA', 288),
('GI', 'Gibraltar', 'GIB', 292),
('GR', 'Greece', 'GRC', 300),
('GL', 'Greenland', 'GRL', 304),
('GD', 'Grenada', 'GRD', 308),
('GP', 'Guadeloupe', 'GLP', 312),
('GU', 'Guam', 'GUM', 316),
('GT', 'Guatemala', 'GTM', 320),
('GN', 'Guinea', 'GIN', 324),
('GW', 'Guinea-Bissau', 'GNB', 624),
('GY', 'Guyana', 'GUY', 328),
('HT', 'Haiti', 'HTI', 332),
('HM', 'Heard Island and Mcdonald Islands', NULL, NULL),
('VA', 'Holy See (Vatican City State)', 'VAT', 336),
('HN', 'Honduras', 'HND', 340),
('HK', 'Hong Kong', 'HKG', 344),
('HU', 'Hungary', 'HUN', 348),
('IS', 'Iceland', 'ISL', 352),
('IN', 'India', 'IND', 356),
('ID', 'Indonesia', 'IDN', 360),
('IR', 'Iran, Islamic Republic of', 'IRN', 364),
('IQ', 'Iraq', 'IRQ', 368),
('IE', 'Ireland', 'IRL', 372),
('IL', 'Israel', 'ISR', 376),
('IT', 'Italy', 'ITA', 380),
('JM', 'Jamaica', 'JAM', 388),
('JP', 'Japan', 'JPN', 392),
('JO', 'Jordan', 'JOR', 400),
('KZ', 'Kazakhstan', 'KAZ', 398),
('KE', 'Kenya', 'KEN', 404),
('KI', 'Kiribati', 'KIR', 296),
('KP', 'Korea, Democratic People''s Republic of', 'PRK', 408),
('KR', 'Korea, Republic of', 'KOR', 410),
('KW', 'Kuwait', 'KWT', 414),
('KG', 'Kyrgyzstan', 'KGZ', 417),
('LA', 'Lao People''s Democratic Republic', 'LAO', 418),
('LV', 'Latvia', 'LVA', 428),
('LB', 'Lebanon', 'LBN', 422),
('LS', 'Lesotho', 'LSO', 426),
('LR', 'Liberia', 'LBR', 430),
('LY', 'Libyan Arab Jamahiriya', 'LBY', 434),
('LI', 'Liechtenstein', 'LIE', 438),
('LT', 'Lithuania', 'LTU', 440),
('LU', 'Luxembourg', 'LUX', 442),
('MO', 'Macao', 'MAC', 446),
('MK', 'Macedonia, the Former Yugoslav Republic of', 'MKD', 807),
('MG', 'Madagascar', 'MDG', 450),
('MW', 'Malawi', 'MWI', 454),
('MY', 'Malaysia', 'MYS', 458),
('MV', 'Maldives', 'MDV', 462),
('ML', 'Mali', 'MLI', 466),
('MT', 'Malta', 'MLT', 470),
('MH', 'Marshall Islands', 'MHL', 584),
('MQ', 'Martinique', 'MTQ', 474),
('MR', 'Mauritania', 'MRT', 478),
('MU', 'Mauritius', 'MUS', 480),
('YT', 'Mayotte', NULL, NULL),
('MX', 'Mexico', 'MEX', 484),
('FM', 'Micronesia, Federated States of', 'FSM', 583),
('MD', 'Moldova, Republic of', 'MDA', 498),
('MC', 'Monaco', 'MCO', 492),
('MN', 'Mongolia', 'MNG', 496),
('MS', 'Montserrat', 'MSR', 500),
('MA', 'Morocco', 'MAR', 504),
('MZ', 'Mozambique', 'MOZ', 508),
('MM', 'Myanmar', 'MMR', 104),
('NA', 'Namibia', 'NAM', 516),
('NR', 'Nauru', 'NRU', 520),
('NP', 'Nepal', 'NPL', 524),
('NL', 'Netherlands', 'NLD', 528),
('AN', 'Netherlands Antilles', 'ANT', 530),
('NC', 'New Caledonia', 'NCL', 540),
('NZ', 'New Zealand', 'NZL', 554),
('NI', 'Nicaragua', 'NIC', 558),
('NE', 'Niger', 'NER', 562),
('NG', 'Nigeria', 'NGA', 566),
('NU', 'Niue', 'NIU', 570),
('NF', 'Norfolk Island', 'NFK', 574),
('MP', 'Northern Mariana Islands', 'MNP', 580),
('NO', 'Norway', 'NOR', 578),
('OM', 'Oman', 'OMN', 512),
('PK', 'Pakistan', 'PAK', 586),
('PW', 'Palau', 'PLW', 585),
('PS', 'Palestinian Territory, Occupied', NULL, NULL),
('PA', 'Panama', 'PAN', 591),
('PG', 'Papua New Guinea', 'PNG', 598),
('PY', 'Paraguay', 'PRY', 600),
('PE', 'Peru', 'PER', 604),
('PH', 'Philippines', 'PHL', 608),
('PN', 'Pitcairn', 'PCN', 612),
('PL', 'Poland', 'POL', 616),
('PT', 'Portugal', 'PRT', 620),
('PR', 'Puerto Rico', 'PRI', 630),
('QA', 'Qatar', 'QAT', 634),
('RE', 'Reunion', 'REU', 638),
('RO', 'Romania', 'ROM', 642),
('RU', 'Russian Federation', 'RUS', 643),
('RW', 'Rwanda', 'RWA', 646),
('SH', 'Saint Helena', 'SHN', 654),
('KN', 'Saint Kitts and Nevis', 'KNA', 659),
('LC', 'Saint Lucia', 'LCA', 662),
('PM', 'Saint Pierre and Miquelon', 'SPM', 666),
('VC', 'Saint Vincent and the Grenadines', 'VCT', 670),
('WS', 'Samoa', 'WSM', 882),
('SM', 'San Marino', 'SMR', 674),
('ST', 'Sao Tome and Principe', 'STP', 678),
('SA', 'Saudi Arabia', 'SAU', 682),
('SN', 'Senegal', 'SEN', 686),
('CS', 'Serbia and Montenegro', NULL, NULL),
('SC', 'Seychelles', 'SYC', 690),
('SL', 'Sierra Leone', 'SLE', 694),
('SG', 'Singapore', 'SGP', 702),
('SK', 'Slovakia', 'SVK', 703),
('SI', 'Slovenia', 'SVN', 705),
('SB', 'Solomon Islands', 'SLB', 90),
('SO', 'Somalia', 'SOM', 706),
('ZA', 'South Africa', 'ZAF', 710),
('GS', 'South Georgia and the South Sandwich Islands', NULL, NULL),
('ES', 'Spain', 'ESP', 724),
('LK', 'Sri Lanka', 'LKA', 144),
('SD', 'Sudan', 'SDN', 736),
('SR', 'Suriname', 'SUR', 740),
('SJ', 'Svalbard and Jan Mayen', 'SJM', 744),
('SZ', 'Swaziland', 'SWZ', 748),
('SE', 'Sweden', 'SWE', 752),
('CH', 'Switzerland', 'CHE', 756),
('SY', 'Syrian Arab Republic', 'SYR', 760),
('TW', 'Taiwan, Province of China', 'TWN', 158),
('TJ', 'Tajikistan', 'TJK', 762),
('TZ', 'Tanzania, United Republic of', 'TZA', 834),
('TH', 'Thailand', 'THA', 764),
('TL', 'Timor-Leste', NULL, NULL),
('TG', 'Togo', 'TGO', 768),
('TK', 'Tokelau', 'TKL', 772),
('TO', 'Tonga', 'TON', 776),
('TT', 'Trinidad and Tobago', 'TTO', 780),
('TN', 'Tunisia', 'TUN', 788),
('TR', 'Turkey', 'TUR', 792),
('TM', 'Turkmenistan', 'TKM', 795),
('TC', 'Turks and Caicos Islands', 'TCA', 796),
('TV', 'Tuvalu', 'TUV', 798),
('UG', 'Uganda', 'UGA', 800),
('UA', 'Ukraine', 'UKR', 804),
('AE', 'United Arab Emirates', 'ARE', 784),
('GB', 'United Kingdom', 'GBR', 826),
('US', 'United States', 'USA', 840),
('UM', 'United States Minor Outlying Islands', NULL, NULL),
('UY', 'Uruguay', 'URY', 858),
('UZ', 'Uzbekistan', 'UZB', 860),
('VU', 'Vanuatu', 'VUT', 548),
('VE', 'Venezuela', 'VEN', 862),
('VN', 'Viet Nam', 'VNM', 704),
('VG', 'Virgin Islands, British', 'VGB', 92),
('VI', 'Virgin Islands, U.s.', 'VIR', 850),
('WF', 'Wallis and Futuna', 'WLF', 876),
('EH', 'Western Sahara', 'ESH', 732),
('YE', 'Yemen', 'YEM', 887),
('ZM', 'Zambia', 'ZMB', 894),
('ZW', 'Zimbabwe', 'ZWE', 716);

CREATE TABLE IF NOT EXISTS `states` (
  `id` int(11) NOT NULL auto_increment,
  `name` char(40) collate utf8_unicode_ci NOT NULL default '',
  `abbrev` char(2) collate utf8_unicode_ci NOT NULL default '',
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=66 ;

INSERT INTO `states` (`id`, `name`, `abbrev`) VALUES
(1, 'Alaska', 'AK'),
(2, 'Alabama', 'AL'),
(3, 'American Samoa', 'AS'),
(4, 'Arizona', 'AZ'),
(5, 'Arkansas', 'AR'),
(6, 'California', 'CA'),
(7, 'Colorado', 'CO'),
(8, 'Connecticut', 'CT'),
(9, 'Delaware', 'DE'),
(10, 'District of Columbia', 'DC'),
(11, 'Federated States of Micronesia', 'FM'),
(12, 'Florida', 'FL'),
(13, 'Georgia', 'GA'),
(14, 'Guam', 'GU'),
(15, 'Hawaii', 'HI'),
(16, 'Idaho', 'ID'),
(17, 'Illinois', 'IL'),
(18, 'Indiana', 'IN'),
(19, 'Iowa', 'IA'),
(20, 'Kansas', 'KS'),
(21, 'Kentucky', 'KY'),
(22, 'Louisiana', 'LA'),
(23, 'Maine', 'ME'),
(24, 'Marshall Islands', 'MH'),
(25, 'Maryland', 'MD'),
(26, 'Massachusetts', 'MA'),
(27, 'Michigan', 'MI'),
(28, 'Minnesota', 'MN'),
(29, 'Mississippi', 'MS'),
(30, 'Missouri', 'MO'),
(31, 'Montana', 'MT'),
(32, 'Nebraska', 'NE'),
(33, 'Nevada', 'NV'),
(34, 'New Hampshire', 'NH'),
(35, 'New Jersey', 'NJ'),
(36, 'New Mexico', 'NM'),
(37, 'New York', 'NY'),
(38, 'North Carolina', 'NC'),
(39, 'North Dakota', 'ND'),
(40, 'Northern Mariana Islands', 'MP'),
(41, 'Ohio', 'OH'),
(42, 'Oklahoma', 'OK'),
(43, 'Oregon', 'OR'),
(44, 'Palau', 'PW'),
(45, 'Pennsylvania', 'PA'),
(46, 'Puerto Rico', 'PR'),
(47, 'Rhode Island', 'RI'),
(48, 'South Carolina', 'SC'),
(49, 'South Dakota', 'SD'),
(50, 'Tennessee', 'TN'),
(51, 'Texas', 'TX'),
(52, 'Utah', 'UT'),
(53, 'Vermont', 'VT'),
(54, 'Virgin Islands', 'VI'),
(55, 'Virginia', 'VA'),
(56, 'Washington', 'WA'),
(57, 'West Virginia', 'WV'),
(58, 'Wisconsin', 'WI'),
(59, 'Wyoming', 'WY'),
(60, 'Armed Forces Africa', 'AE'),
(61, 'Armed Forces Americas (except Canada)', 'AA'),
(62, 'Armed Forces Canada', 'AE'),
(63, 'Armed Forces Europe', 'AE'),
(64, 'Armed Forces Middle East', 'AE'),
(65, 'Armed Forces Pacific', 'AP');